"""add is_archived column to products

Revision ID: 2e1ff04195dc
Revises: 47fe2ab516a0
Create Date: 2026-04-06 00:26:13.171057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1ff04195dc'
down_revision: Union[str, Sequence[str], None] = '47fe2ab516a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default false to avoid NOT NULL constraint errors on existing rows
    op.add_column('products', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_products_is_archived'), 'products', ['is_archived'], unique=False)
    # Remove server default after column is populated
    op.alter_column('products', 'is_archived', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_archived'), table_name='products')
    op.drop_column('products', 'is_archived')
    # ### end Alembic commands ###
