"""initial schema with audit fields and feature flags

Revision ID: 567e8d2d25c3
Revises: 
Create Date: 2026-03-06 16:06:36.751231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '567e8d2d25c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_feature_name'), 'feature_flags', ['feature_name'], unique=True)
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('adjusted_by', sa.String(), nullable=True),
    sa.Column('previous_stock', sa.Integer(), nullable=True),
    sa.Column('new_stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_adjustments_id'), 'stock_adjustments', ['id'], unique=False)
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('customers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.add_column('products', sa.Column('hsn_code', sa.String(), nullable=True))
    op.add_column('products', sa.Column('unit_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('min_stock_level', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.add_column('purchase_invoices', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('purchase_invoices', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('purchase_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_purchase_invoices_is_deleted'), 'purchase_invoices', ['is_deleted'], unique=False)
    op.add_column('sales_bills', sa.Column('status', sa.String(), nullable=True))
    op.add_column('sales_bills', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('sales_bills', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('sales_bills', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_sales_bills_is_deleted'), 'sales_bills', ['is_deleted'], unique=False)
    op.add_column('stock_ledger', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('suppliers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_suppliers_is_deleted'), 'suppliers', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_suppliers_is_deleted'), table_name='suppliers')
    op.drop_column('suppliers', 'is_deleted')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_column('stock_ledger', 'notes')
    op.drop_index(op.f('ix_sales_bills_is_deleted'), table_name='sales_bills')
    op.drop_column('sales_bills', 'is_deleted')
    op.drop_column('sales_bills', 'updated_at')
    op.drop_column('sales_bills', 'created_at')
    op.drop_column('sales_bills', 'status')
    op.drop_index(op.f('ix_purchase_invoices_is_deleted'), table_name='purchase_invoices')
    op.alter_column('purchase_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('purchase_invoices', 'is_deleted')
    op.drop_column('purchase_invoices', 'updated_at')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'min_stock_level')
    op.drop_column('products', 'category')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'unit_type')
    op.drop_column('products', 'hsn_code')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.drop_column('customers', 'is_deleted')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_index(op.f('ix_stock_adjustments_id'), table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_feature_name'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
