"""Add stock adjustments table

Revision ID: cceef20c219d
Revises: d63e38d38728
Create Date: 2026-03-06 17:14:37.510808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cceef20c219d'
down_revision: Union[str, Sequence[str], None] = 'd63e38d38728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_adjustments', sa.Column('stock_batch_id', sa.Integer(), nullable=False))
    op.alter_column('stock_adjustments', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'stock_adjustments', 'stock_batches', ['stock_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.alter_column('stock_adjustments', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('stock_adjustments', 'stock_batch_id')
    # ### end Alembic commands ###
