"""add audit columns and new tables with defaults

Revision ID: d63e38d38728
Revises: 567e8d2d25c3
Create Date: 2026-03-06 16:25:53.459602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63e38d38728'
down_revision: Union[str, Sequence[str], None] = '567e8d2d25c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('customers', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.add_column('products', sa.Column('hsn_code', sa.String(), nullable=True))
    op.add_column('products', sa.Column('unit_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('min_stock_level', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.add_column('purchase_invoices', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('purchase_invoices', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('purchase_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_purchase_invoices_is_deleted'), 'purchase_invoices', ['is_deleted'], unique=False)
    op.add_column('sales_bills', sa.Column('status', sa.String(), nullable=True))
    op.add_column('sales_bills', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sales_bills', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sales_bills', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_sales_bills_is_deleted'), 'sales_bills', ['is_deleted'], unique=False)
    op.add_column('stock_ledger', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('suppliers', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_suppliers_is_deleted'), 'suppliers', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_suppliers_is_deleted'), table_name='suppliers')
    op.drop_column('suppliers', 'is_deleted')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_column('stock_ledger', 'notes')
    op.drop_index(op.f('ix_sales_bills_is_deleted'), table_name='sales_bills')
    op.drop_column('sales_bills', 'is_deleted')
    op.drop_column('sales_bills', 'updated_at')
    op.drop_column('sales_bills', 'created_at')
    op.drop_column('sales_bills', 'status')
    op.drop_index(op.f('ix_purchase_invoices_is_deleted'), table_name='purchase_invoices')
    op.alter_column('purchase_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('purchase_invoices', 'is_deleted')
    op.drop_column('purchase_invoices', 'updated_at')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'min_stock_level')
    op.drop_column('products', 'category')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'unit_type')
    op.drop_column('products', 'hsn_code')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.drop_column('customers', 'is_deleted')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    # ### end Alembic commands ###
